TR3FIR-478 Adding support to setup an already initialized CPU2
tokenize-inc/embassy pull request #29
Opened 2024-11-05 19:29 UTC by TylerGajewski-Token

2024-11-06 09:04 UTC, lukasz-zajac requested changes
Needs version bump

2024-11-06 14:06 UTC, dboleyToken approved these changes
These changes don't affect normal operation with non SBSFU bootloader. So are safe to pull into current halo develop.

2024-11-12 08:30 UTC, lukasz-zajac commented
@TylerGajewski-Token I forgot that we don't use artifactory for embassy anymore, so there is no need to bump anything. My mistake, sorry. You can remove the last commit you've added

2024-11-12 14:38 UTC, lukasz-zajac commented on embassy-usb/Cargo.toml
> +version = "0.2.1"
If you bumped this only because of my previous review, this should also be removed.

2024-11-12 14:55 UTC, lukasz-zajac approved these changes

2024-11-12 14:56 UTC, merged